# Version 2.0
substitutions:
  # Unique device ID in HA
  deviceid: "airco_bedroom"
  # Unique device name in HA (sensor names will be prefixed by this name)
  devicename: "Airco bedroom"
  # The WiFi network to connect to
  wifi_ssid: !secret wifi_ssid
  # The WiFi password
  wifi_password: !secret wifi_password
  # Web auth username
  username: !secret username
  # Web auth password
  password: !secret password

esphome:
  name: ${deviceid}
  platform: ESP8266
  board: d1_mini
  platformio_options:
    # Run CPU at 160Mhz to fix mhi_ac_ctrl_core.loop error: -2
    board_build.f_cpu: 160000000L
  includes:
    - mhi_ac_ctrl.h
    - MHI-AC-Ctrl-core.h
    - MHI-AC-Ctrl-core.cpp

# Enable this for current units, supporting the larger framesize
# Comment if you encounter mhi_ac_ctrl_core.loop error: -2 errors and uncomment the legacy_framesize file
<<: !include conf/large_framesize.yaml
# Uncomment this to allow for a working configuration on floor units or older units
# <<: !include conf/legacy_framesize.yaml

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  ap:
    ssid: ${devicename}

captive_portal:

web_server:
  log: false
  port: 80
  auth:
    username: ${username}
    password: ${password}

logger:
  level: DEBUG
  baud_rate: 0

ota:

button:
  - platform: safe_mode
    name: Reboot to safe mode
  - platform: restart
    name: Reboot
    entity_category: diagnostic

climate:
  - platform: custom
    lambda: |-
      auto mhi_ac_ctrl = new MhiAcCtrl();
      App.register_component(mhi_ac_ctrl);
      return {mhi_ac_ctrl};

    climates:
      - name: "${devicename}"
        id: ${deviceid}

api:
  reboot_timeout: 0s
  services:
    # Call the set_vanes service from HA to set the vane position
    # Needed because the ESPHome Climate class does not support this natively
    # Possible values: 1-4: static positions, 5: swing, 0: unknown
    - service: set_vanes
      variables:
        value: int
      then:
        - lambda: |-
            return ((MhiAcCtrl*)id(${deviceid}))->set_vanes(value);

binary_sensor:
  - platform: custom
    lambda: |-
      return ((MhiAcCtrl*)id(${deviceid}))->get_binary_sensors();

    binary_sensors:
      - name: defrost

text_sensor:
  - platform: version
    name: ESPHome Version
  - platform: wifi_info
    ip_address:
      name: IP
    ssid:
      name: SSID
    bssid:
      name: BSSID
  - platform: custom
    lambda: |-
      return ((MhiAcCtrl*)id(${deviceid}))->get_text_sensors();

    text_sensors:
      - name: Compressor protection status


